name: Build Plugin

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Download Paper API
        run: curl -o paper.jar https://api.papermc.io/v2/projects/paper/versions/1.21.4/builds/1/downloads/paper-1.21.4-1.jar

      - name: Compile Plugin
        run: |
          mkdir -p out/classes
          javac -classpath paper.jar -d out/classes $(find src -name "*.java")
          jar cvf YamanClan.jar -C out/classes . plugin.yml

      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: YamanClan
          path: YamanClan.jar
